### PR TITLE
OCPBUGS-13242: Added trailing 0 to ipv6 ranges that end in ":" [Backport 4.10]

### PR DESCRIPTION
**Pull request by nicklesimba**
ipv6 ranges ending in a colon, such as a trail of zeroes denoted by "::" result in the storage engine failing to process the range, because ranges are expected to begin and end with alphanumerical characters to meet CRD requirements. Thus we append a 0 to any ranges that meet this criteria because it is functionally equivalent.

### CODE REVIEW

**Comment by zshi-redhat** [comment]
@nicklesimba Is this a clean cherry-pick? looks like it is, but I don't see the auto cherry-pick message in the commit.

**Comment by nicklesimba** [comment]
@zshi-redhat It should be. This is what the 4.11/4.12 etc. backports looked like as well - and I got the commit via `git cherry-pick` command in all cases.

**Pull request merged**
