### PR TITLE
Bug 2009493: Release on cancel 4.9

### PR DESCRIPTION
**Pull request by dougbtv**

### CODE REVIEW

**Comment by dougbtv** [comment]
@sdodson We did make this update as a sync with upstream. One thing that the release on cancel update relies on is another fix that adds a context which required a refactor, this was to fix runaway processes (see BZ). 

It's worth noting that these changes impact only the Whereabouts CNI container image.

Being a sync to upstream, it does catch some other functionality that I don't believe to be particularly risky, however also additionally included:

* A bug fix to the IP reconciliation
* Tooling updates

**Comment by stleerh** [comment]
It's hard to gauge the risk of this large change even though it's limited to the Whereabouts CNI container.  I would like to request QE to document their testing and results, and show how this scalability issue has been addressed.

**Comment by dougbtv** [comment]
There is some amount of risk, however, this set of changes does provide a significant performance fix. There's further scale questions to be answered, but this is our path forward for the short term.

To measure how long it took to launch 50 pods, I took these three steps... Using clusters of equal horsepower and ran against two separate clusters.

* I did an `oc create -f` the provided `whereabouts-test-conf.yaml`
    - NOTE: You must change the `master:` parameter for macvlan to match a system's actual network interface card name.
    - NOTE: You should also use a new project with no other pods running.
* I created the file provided as `whereabouts-test-pod.yaml`
* I then ran the provided script which `oc create`'s the replica set, then it show when all pods became ready with Whereabouts, at which times.

`whereabouts-test-conf.yaml`

```
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: whereabouts-conf
spec:
  config: '{
      "cniVersion": "0.3.0",
      "name": "whereaboutsexample",
      "type": "macvlan",
      "master": "ens4",
      "mode": "bridge",
      "ipam": {
        "type": "whereabouts",
        "range": "10.2.0.0/16"
      }
    }'
```

`whereabouts-test-pod.yaml`


```
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: whereabouts-test
  labels:
    app: whereabouts-test
    tier: whereabouts-test
spec:
  # modify replicas according to your case
  replicas: 50
  selector:
    matchLabels:
      tier: whereabouts-test
  template:
    metadata:
      labels:
        tier: whereabouts-test
      annotations:
        k8s.v1.cni.cncf.io/networks: whereabouts-conf
    spec:
      containers:
      - name: samplepod
        command: ["/bin/ash", "-c", "trap : TERM INT; sleep infinity & wait"]
        image: quay.io/dougbtv/alpine:latest
```

`test-whereabouts.sh`


```
#!/bin/bash
oc create -f whereabouts-test-pod.yaml

echo Starting at $(date)
while [ true ]; do
  oc get pods | grep Running | wc -l | grep 50 > /dev/null
  exitcode=$?
  if [ $exitcode -eq 0 ]; then
    break
  fi
  sleep 1
done
echo Finished at $(date)
```

(Make sure to `chmod +x` on the script)

I then ran it against a 4.10 cluster from CI which has this fix applied, my results were 12 seconds.

```
./test-whereabouts.sh 
replicaset.apps/whereabouts-test created
Starting at Mon Nov 1 04:06:57 PM EDT 2021
Finished at Mon Nov 1 04:07:09 PM EDT 2021
```

Against a 4.9 cluster which does not have this fix, my results were 94 seconds.

```
./test-whereabouts.sh 
replicaset.apps/whereabouts-test created
Starting at Mon Nov 1 04:49:54 PM EDT 2021
Finished at Mon Nov 1 04:51:28 PM EDT 2021
```

**Comment by stleerh** [comment]
@doug Thanks for the explanation.

**Pull request merged**
