### PR TITLE
[release-4.13] OCPBUGS-27958:  Enable reconciler configuration

### PR DESCRIPTION
**Pull request by liornoy**
**Attention!**
This **is not a clean cherry-pick** - The `Dockerfile.openshift` was modified manually to bump
the base image to Go v1.20.

Backport of #240 
Related to: [openshift/cluster-network-operator#2220](https://github.com/openshift/cluster-network-operator/pull/2220)

Enable whereabouts-reconciler configuration via a ConfigMap.

### CODE REVIEW

**Comment by dougbtv** [comment]
thanks for the note on the dockerfile, that's totally acceptable the way you went about, appreciate it, good eye on the dockerfile change.

**Comment by dougbtv** [comment]
I'm starting to wonder if go 1.20 isn't available for 4.13, the image build failed with:

```
Trying to pull registry.ci.openshift.org/ocp/builder:rhel-8-golang-1.20-openshift-4.13...
Warning: Pull failed, retrying in 5s ...
```

**Comment by liornoy** [comment]
> I'm starting to wonder if go 1.20 isn't available for 4.13, the image build failed with:
> 
> ```
> Trying to pull registry.ci.openshift.org/ocp/builder:rhel-8-golang-1.20-openshift-4.13...
> Warning: Pull failed, retrying in 5s ...
> ```

You are right, there is not 1.20 image for 4.13,
I filed a new commit to use gocron v1, and stay with 1.19.

**Comment by liornoy** [comment]
Regarding the modification in the tests, removed the `seconds` from the - "updatedCronWithSeconds" because with v2 we used the JobDefinition struct to set the "withSeconds" on the scheduler, and we don't have this struct in v1.
With that said, we don't actually use the "withSeconds" on v2 anyways because this is hard-coded to false, see [here](https://github.com/openshift/whereabouts-cni/blob/b24729e5b72c2341a5bf86ff05a5ed14f23a9e09/pkg/reconciler/config.go#L34)

**Pull request merged**
